# POST PRODUCT
curl --header "Content-Type: application/json" \
  --request POST \
  --data ' {
              "name": "Nova Pessoa",
              "salary": 8000.0,
              "department": {
                  "id": 1,
                  "name":"21"
                  }
}' \
http://localhost:8080/people
